// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "1586578b-3214-42a5-92f3-8832728a651d";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onAreaChange();

float air_Flow_Volume;
float area;
float current;
float energy;
float humidity;
float operatioanl_time;
float pF;
float power;
float temperature;
float windspeed;
int rpm;
int voltage;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(air_Flow_Volume, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(area, READWRITE, ON_CHANGE, onAreaChange);
  ArduinoCloud.addProperty(current, READ, 5 * SECONDS, NULL);
  ArduinoCloud.addProperty(energy, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(humidity, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(operatioanl_time, READ, 5 * SECONDS, NULL);
  ArduinoCloud.addProperty(pF, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(power, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperature, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(windspeed, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(rpm, READ, 5 * SECONDS, NULL);
  ArduinoCloud.addProperty(voltage, READ, 10 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
